// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: undo_log.proto

package mysql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbSqlUndoLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SqlType     int32           `protobuf:"varint,1,opt,name=SqlType,proto3" json:"SqlType,omitempty"`
	SchemaName  string          `protobuf:"bytes,2,opt,name=SchemaName,proto3" json:"SchemaName,omitempty"`
	TableName   string          `protobuf:"bytes,3,opt,name=TableName,proto3" json:"TableName,omitempty"`
	LockKey     string          `protobuf:"bytes,4,opt,name=LockKey,proto3" json:"LockKey,omitempty"`
	BeforeImage *PbTableRecords `protobuf:"bytes,5,opt,name=BeforeImage,proto3" json:"BeforeImage,omitempty"`
	AfterImage  *PbTableRecords `protobuf:"bytes,6,opt,name=AfterImage,proto3" json:"AfterImage,omitempty"`
}

func (x *PbSqlUndoLog) Reset() {
	*x = PbSqlUndoLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_undo_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbSqlUndoLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbSqlUndoLog) ProtoMessage() {}

func (x *PbSqlUndoLog) ProtoReflect() protoreflect.Message {
	mi := &file_undo_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbSqlUndoLog.ProtoReflect.Descriptor instead.
func (*PbSqlUndoLog) Descriptor() ([]byte, []int) {
	return file_undo_log_proto_rawDescGZIP(), []int{0}
}

func (x *PbSqlUndoLog) GetSqlType() int32 {
	if x != nil {
		return x.SqlType
	}
	return 0
}

func (x *PbSqlUndoLog) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *PbSqlUndoLog) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *PbSqlUndoLog) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *PbSqlUndoLog) GetBeforeImage() *PbTableRecords {
	if x != nil {
		return x.BeforeImage
	}
	return nil
}

func (x *PbSqlUndoLog) GetAfterImage() *PbTableRecords {
	if x != nil {
		return x.AfterImage
	}
	return nil
}

type PbBranchUndoLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XID             string          `protobuf:"bytes,1,opt,name=XID,proto3" json:"XID,omitempty"`
	BranchSessionID int64           `protobuf:"varint,2,opt,name=BranchSessionID,proto3" json:"BranchSessionID,omitempty"`
	SqlUndoLogs     []*PbSqlUndoLog `protobuf:"bytes,3,rep,name=SqlUndoLogs,proto3" json:"SqlUndoLogs,omitempty"`
}

func (x *PbBranchUndoLog) Reset() {
	*x = PbBranchUndoLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_undo_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbBranchUndoLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbBranchUndoLog) ProtoMessage() {}

func (x *PbBranchUndoLog) ProtoReflect() protoreflect.Message {
	mi := &file_undo_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbBranchUndoLog.ProtoReflect.Descriptor instead.
func (*PbBranchUndoLog) Descriptor() ([]byte, []int) {
	return file_undo_log_proto_rawDescGZIP(), []int{1}
}

func (x *PbBranchUndoLog) GetXID() string {
	if x != nil {
		return x.XID
	}
	return ""
}

func (x *PbBranchUndoLog) GetBranchSessionID() int64 {
	if x != nil {
		return x.BranchSessionID
	}
	return 0
}

func (x *PbBranchUndoLog) GetSqlUndoLogs() []*PbSqlUndoLog {
	if x != nil {
		return x.SqlUndoLogs
	}
	return nil
}

var File_undo_log_proto protoreflect.FileDescriptor

var file_undo_log_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x6e, 0x64, 0x6f, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x1a, 0x13, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a,
	0x0c, 0x50, 0x62, 0x53, 0x71, 0x6c, 0x55, 0x6e, 0x64, 0x6f, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x71, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x53, 0x71, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x12,
	0x37, 0x0a, 0x0b, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x50, 0x62, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x0b, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x79, 0x73, 0x71, 0x6c, 0x2e, 0x50, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x0a, 0x41, 0x66, 0x74, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22,
	0x84, 0x01, 0x0a, 0x0f, 0x50, 0x62, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x55, 0x6e, 0x64, 0x6f,
	0x4c, 0x6f, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x58, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x58, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x35, 0x0a, 0x0b, 0x53, 0x71, 0x6c, 0x55, 0x6e, 0x64, 0x6f, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x50, 0x62, 0x53,
	0x71, 0x6c, 0x55, 0x6e, 0x64, 0x6f, 0x4c, 0x6f, 0x67, 0x52, 0x0b, 0x53, 0x71, 0x6c, 0x55, 0x6e,
	0x64, 0x6f, 0x4c, 0x6f, 0x67, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6d, 0x79, 0x73, 0x71,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_undo_log_proto_rawDescOnce sync.Once
	file_undo_log_proto_rawDescData = file_undo_log_proto_rawDesc
)

func file_undo_log_proto_rawDescGZIP() []byte {
	file_undo_log_proto_rawDescOnce.Do(func() {
		file_undo_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_undo_log_proto_rawDescData)
	})
	return file_undo_log_proto_rawDescData
}

var file_undo_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_undo_log_proto_goTypes = []interface{}{
	(*PbSqlUndoLog)(nil),    // 0: mysql.PbSqlUndoLog
	(*PbBranchUndoLog)(nil), // 1: mysql.PbBranchUndoLog
	(*PbTableRecords)(nil),  // 2: mysql.PbTableRecords
}
var file_undo_log_proto_depIdxs = []int32{
	2, // 0: mysql.PbSqlUndoLog.BeforeImage:type_name -> mysql.PbTableRecords
	2, // 1: mysql.PbSqlUndoLog.AfterImage:type_name -> mysql.PbTableRecords
	0, // 2: mysql.PbBranchUndoLog.SqlUndoLogs:type_name -> mysql.PbSqlUndoLog
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_undo_log_proto_init() }
func file_undo_log_proto_init() {
	if File_undo_log_proto != nil {
		return
	}
	file_table_records_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_undo_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbSqlUndoLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_undo_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbBranchUndoLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_undo_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_undo_log_proto_goTypes,
		DependencyIndexes: file_undo_log_proto_depIdxs,
		MessageInfos:      file_undo_log_proto_msgTypes,
	}.Build()
	File_undo_log_proto = out.File
	file_undo_log_proto_rawDesc = nil
	file_undo_log_proto_goTypes = nil
	file_undo_log_proto_depIdxs = nil
}
